os:
- linux
- osx
language: node_js
node_js:
- node
script: npm run build
env:
  secure: sY9k2FzPBjbW3R3tVg0NlGDiKKX1qinMIf8Pe2bQvBDUkL4U5FhLfrF9xMGJJvJo5b88M7IwEDZL7irIwXKT4YnTGeaAcTWqL8tUFusZkCait9dJCcb+Uq2E2T2S6iihiaEurUe5l2DA8H3cG9+KFZqSsCQ1qdxIfkhZ2Zv4BwoI7y8nzrR5wp9ufYtxfiMQhjVBiYJQvJDNltaXigYCjYcIT0Lz+y11N7jl+DjLWaF0p2iDFdnBIlhUHzXOBL4gnWwOAY0BKGfhZ3K7lwRapSfiky/k/OHR5ZVRMBhdlL5ehp3dXz1+C1U+pwJ3v1ZtGS0zmCKAjREb4e/u4bvOsxfBIG5Yl/3pr46DXECvyNXcFnUQ1EyOvUKZYVOoK1RthoJR/fh7Qc6Adhd9mzirUxNL74OfC8oU4PPCwUhYChZWJyo+YM+0Zdnm8RNNxzJxx6dEn0M53CBzo2T0ckqxwu+WM+59jvffZ3VPT3g5TKaEPRyYfBC1cZA6Qzv7MiqZRTf5LbJnX5W5tPCbRpsKlwOhLhztiB38a2tfFmIU2drWkV0YJUFWTWzW+YfhijK8VX/MZrtZRnGc4eKlEW7zz1/TsBJdaGtkDy0QY1/RfmH5exXBOo9no0ZZR3aV2JG+tQEsjmjQHhhzbtCYLGvYVFpj8qm9OWwkOsONO6aq5v8=
