os:
- linux
- osx
language: node_js
node_js:
- node
script: npm run build
env:
  secure: SEEff7FtID5HBlVMwWWP4ABVHPIDyanjd4eRiIXRV1qE50K9xalc8TvvFuLHu4lOVqFinyayLG41810g5mnPhS4PjI7WlQ8UglqkZSVjHc6jyx++meR8TvQOD4gpu11g5k3qni4PLidERrDuGcVutlDZi4Spot6MOhCzviaUWNJODrxGeqR6BeQ+jTYO2kGnT4Emj6wzGgrcNV/EFazwWKZpSRMHAfazwraUnPS8oRIq/g6uulbOg//mcPR2E4n6975jcCdP83er5NWBrhwhK8bz6zx3CYQ+8a7rpx5VNwTIOWZmy4yGKDjPvOhb6dTR4NOeSd/3fxfFu8pZ7bLho8OnG8Ziwcgq2G0reWu/Pc06DSlxWLjiWXHUFX5Ch31Q7o0AcmukpGjKILu9rEMhWrWKSNJNGZc/gfEmrF3wcE6a/Pjy5ST/H4pEsceTGeeKmN0QrC1mjPBeC+7S6GeJHYr7mINY7V2TeBXExymN5/9PDtLDCvRUDF3gn25kJoU/eHTLp3DEsyqUED3QbR7zECKWAweLGQMUcc7QtELJqrXCyLSVkAXn9PRIAfqYnZI2+v2u074DmOsOsedRhSiqZ69+aG57llOw55jxl9XXB0Cjxc/LSLh7iay20R6+4sa8eQjB+ENYWOSya0/nb6OfuozonM38gCqaEneEFxhmMk0=
